### ISSUE TITLE
panels always in sync

### ISSUE THREAD

**Issue by mustaruhtinas** [dawsers/dual-pane.yazi#3]
This is a great plugin, might finally be able to move away completely from mc, but I am not sure I set everything up properly.

I followed the instructions, however, when toggled, panels are always in sync.

I normally build yazi from the latest git commit, and the only other change in init.lua is a function to also list modified time and size.

**Comment by dawsers** [comment]
Thank you. Using git is also probably wise, as there are a few fixes that make dual-pane work better.

Did you follow the tutorial? It gives a rough overview of how things work. For example, like you said, if you simply open dual-pane and there is just one tab, both panes will be in sync and show that tab. If you have more than one tab, you will see different ones in each pane.

If you are using the key bindings from the README, and you start dual-pane with just one tab, press `t` to create another one, and then you will have different tabs in each pane. Use `<TAB>` to move from one pane to the other, and `[`, `]` to navigate tabs (or a number) in the active pane. You can keep on creating tabs or modify their cwd by navigating as usual.

Let me know if this clarifies things a bit.

**Comment by mustaruhtinas** [comment]
Ah, I see, so basically tabs are required for it to work. Was not aware of this, but it makes sense in hindsight.
Either skipped or did not properly read / understood relevant section. Sorry for your time.
Obviously working perfectly.

**Comment by dawsers** [comment]
No problem. I hope you can make it work for your needs.

Think of a tab as storage for a location. If you want to copy things from one place to another, you need two locations. I use static bookmarks to change a tab to a memorized location, and a few tabs to point to locations I use frequently. So with bookmarks to the usual 8-10 directories (Downloads, Documents etc.) and 3-4 tabs, I cover most workflows with just a few keystrokes.

**Comment by mustaruhtinas** [comment]
It is very clear and straightforward now. I was thinking in terms of mc, which I have used for many years now, hence the confusion.
I must admit this plugin (in fact, all three of them) is fantastic, I really wanted a dual-pane yazi.
Thank you!
